# Model parameters:
image_size: 256
in_channels: 3
out_channels: 3
weight_init: null

num_layers: 7
num_features: 128

# Training process:
num_epochs: 100
batch_size: 32
learning_rate: 0.0003
load_checkpoint: false
save_checkpoint: true
num_workers: 2
train_name: null
set_seed: false
seed: 42

# Dataset:
dataset: ./dataset
test_size: 0.2

# Checkpoints:
checkpoint_dir: checkpoints
