# Model parameters:
image_size: 256
in_channels: 3
out_channels: 3
embedding_size: 512
weight_init: null

# Training process:
num_epochs: 100
batch_size: 32
generator_learning_rate: 0.0003
discriminator_learning_rate: 0.000003
adv_weight: 1.0
load_checkpoint: false
save_checkpoint: false
num_workers: 2
set_seed: true

# Dataset:
dataset: ./dataset
dataset_mean: [0.5, 0.5, 0.5]
dataset_std: [0.5, 0.5, 0.5]

# Checkpoints:
checkpoint_dir: checkpoints
